# -*- coding: utf-8 -*-
"""
Pone las tildes y la ene en el texto que ve el usuario.

Solo toca zonas seguras: texto entre etiquetas JSX, valores de propiedades de
presentacion y mensajes de error. Nunca nombres de campo, ids, clases ni slugs,
porque de esos dependen los formularios y los filtros de la URL.
"""
import re
import sys
import pathlib

# Palabras inequivocas.
WORDS = {
    "accion": "acción", "Accion": "Acción",
    "proxima": "próxima", "Proxima": "Próxima", "proximo": "próximo", "Proximo": "Próximo",
    "proximas": "próximas", "Proximas": "Próximas", "proximos": "próximos", "Proximos": "Próximos",
    "negociacion": "negociación", "Negociacion": "Negociación",
    "NEGOCIACION": "NEGOCIACIÓN",
    "Jose": "José", "Tobon": "Tobón", "TOBON": "TOBÓN",
    "dia": "día", "dias": "días", "Dia": "Día", "Dias": "Días",
    "estan": "están", "Estan": "Están",
    "telefono": "teléfono", "Telefono": "Teléfono",
    "ultima": "última", "Ultima": "Última", "ultimo": "último", "Ultimo": "Último",
    "ultimos": "últimos", "Ultimos": "Últimos",
    "informacion": "información", "Informacion": "Información",
    "tambien": "también", "Tambien": "También",
    "aqui": "aquí", "Aqui": "Aquí",
    "pagina": "página", "Pagina": "Página",
    "numero": "número", "Numero": "Número", "numeros": "números",
    "mas": "más", "Mas": "Más",
    "segun": "según", "Segun": "Según",
    "despues": "después", "Despues": "Después",
    "categoria": "categoría", "Categoria": "Categoría", "categorias": "categorías",
    "facturacion": "facturación", "Facturacion": "Facturación",
    "calificacion": "calificación", "Calificacion": "Calificación",
    "atencion": "atención", "Atencion": "Atención",
    "campana": "campaña", "Campana": "Campaña", "campanas": "campañas", "Campanas": "Campañas",
    "CAMPANA": "CAMPAÑA",
    "manana": "mañana", "Manana": "Mañana",
    "ano": "año", "anos": "años", "Ano": "Año",
    "tamano": "tamaño", "Tamano": "Tamaño",
    "Espana": "España", "Panama": "Panamá", "Mexico": "México", "Peru": "Perú",
    "automatico": "automático", "Automatico": "Automático",
    "automatica": "automática", "Automatica": "Automática",
    "automaticas": "automáticas", "automaticos": "automáticos",
    "automaticamente": "automáticamente",
    "practica": "práctica", "practicas": "prácticas",
    "electronica": "electrónica", "Electronica": "Electrónica",
    "sesion": "sesión", "Sesion": "Sesión",
    "contrasena": "contraseña", "Contrasena": "Contraseña", "contrasenas": "contraseñas",
    "gestion": "gestión", "Gestion": "Gestión",
    "cotizacion": "cotización", "Cotizacion": "Cotización", "cotizaciones": "cotizaciones",
    "version": "versión", "Version": "Versión",
    "conexion": "conexión", "Conexion": "Conexión",
    "sincronizacion": "sincronización", "Sincronizacion": "Sincronización",
    "configuracion": "configuración", "Configuracion": "Configuración",
    "CONFIGURACION": "CONFIGURACIÓN",
    "integracion": "integración", "Integracion": "Integración",
    "importacion": "importación", "Importacion": "Importación",
    "importaciones": "importaciones",
    "posicion": "posición", "Posicion": "Posición",
    "descripcion": "descripción", "Descripcion": "Descripción",
    "direccion": "dirección", "Direccion": "Dirección",
    "organizacion": "organización", "Organizacion": "Organización",
    "organizaciones": "organizaciones",
    "aplicacion": "aplicación", "Aplicacion": "Aplicación",
    "validacion": "validación",
    "logistica": "logística", "Logistica": "Logística",
    "tecnologia": "tecnología", "Tecnologia": "Tecnología",
    "farmaceutica": "farmacéutica", "Farmaceutica": "Farmacéutica",
    "energia": "energía", "Energia": "Energía",
    "publico": "público", "Publico": "Público", "publica": "pública",
    "construccion": "construcción", "Construccion": "Construcción",
    "educacion": "educación", "Educacion": "Educación",
    "perdida": "pérdida", "Perdida": "Pérdida", "perdidas": "pérdidas", "Perdidas": "Pérdidas",
    "exito": "éxito", "Exito": "Éxito",
    "opcion": "opción", "Opcion": "Opción",
    "asi": "así", "Asi": "Así",
    "rapido": "rápido", "rapida": "rápida", "Rapido": "Rápido",
    "basico": "básico", "basica": "básica",
    "economico": "económico", "economica": "económica",
    "credito": "crédito", "Credito": "Crédito",
    "dificiles": "difíciles", "Dificiles": "Difíciles", "dificil": "difícil", "Dificil": "Difícil",
    "metodo": "método", "Metodo": "Método",
    "asincronico": "asincrónico", "asincronicos": "asincrónicos", "Asincronico": "Asincrónico",
    "sera": "será", "seran": "serán", "Sera": "Será",
    "podras": "podrás", "podra": "podrá",
    "salio": "salió", "Salio": "Salió",
    "quedo": "quedó", "Quedo": "Quedó",
    "acepto": "aceptó", "Acepto": "Aceptó",
    "pidio": "pidió", "Pidio": "Pidió",
    "solicito": "solicitó", "Solicito": "Solicitó",
    "confirmo": "confirmó", "Confirmo": "Confirmó",
    "creo": "creó", "Creo": "Creó",
    "actualizo": "actualizó", "Actualizo": "Actualizó",
    "archivo_v": "archivó",
    "elimino": "eliminó", "Elimino": "Eliminó",
    "modifico": "modificó", "Modifico": "Modificó",
    "fusiono": "fusionó", "Fusiono": "Fusionó",
    "restauro": "restauró", "Restauro": "Restauró",
    "conecto": "conectó", "Conecto": "Conectó",
    "desconecto": "desconectó", "Desconecto": "Desconectó",
    "reembolso_v": "reembolsó",
    "importo": "importó", "Importo": "Importó",
    "movio": "movió", "Movio": "Movió",
    "marco": "marcó",
    "expiro": "expiró", "Expiro": "Expiró",
    "termino": "terminó",
    "Prospeccion": "Prospección", "prospeccion": "prospección",
    "Organico": "Orgánico", "organico": "orgánico",
    "Asesoria": "Asesoría", "asesoria": "asesoría",
    "critica": "crítica", "Critica": "Crítica", "criticas": "críticas", "critico": "crítico",
    "Consultoria": "Consultoría", "consultoria": "consultoría",
    "Diagnostico": "Diagnóstico", "diagnostico": "diagnóstico",
    "analitico": "analítico", "analitica": "analítica",
    "Simulacion": "Simulación", "simulacion": "simulación",
    "Participacion": "Participación", "participacion": "participación",
    "Presentacion": "Presentación", "presentacion": "presentación",
    "Modulo": "Módulo", "modulo": "módulo", "modulos": "módulos", "Modulos": "Módulos",
    "Inscripcion": "Inscripción", "inscripcion": "inscripción",
    "Recomendacion": "Recomendación", "recomendacion": "recomendación",
    "Condicion": "Condición", "condicion": "condición",
    "Ademas": "Además", "ademas": "además",
    "podria": "podría", "podrian": "podrían",
    "deberia": "debería", "deberian": "deberían", "Deberia": "Debería",
    "habria": "habría", "seria": "sería", "serian": "serían", "tenia": "tenía",
    "minimo": "mínimo", "Minimo": "Mínimo", "maximo": "máximo", "Maximo": "Máximo",
    "proposito": "propósito", "Proposito": "Propósito",
    "unico": "único", "unica": "única", "Unico": "Único", "Unica": "Única",
    "facil": "fácil", "Facil": "Fácil", "faciles": "fáciles",
    "util": "útil", "Util": "Útil", "utiles": "útiles", "inutil": "inútil",
    "ningun": "ningún", "Ningun": "Ningún", "algun": "algún", "Algun": "Algún",
    "estara": "estará", "estaran": "estarán",
    "vencio": "venció", "Vencio": "Venció",
    "electronico": "electrónico", "Electronico": "Electrónico",
    "politica": "política", "Politica": "Política", "politicas": "políticas",
    "historico": "histórico", "Historico": "Histórico", "historicos": "históricos",
    "estandar": "estándar", "Estandar": "Estándar",
    "codigo": "código", "Codigo": "Código",
    "pais": "país", "Pais": "País", "paises": "países", "Paises": "Países",
    "PAIS": "PAÍS",
    "linea": "línea", "Linea": "Línea", "lineas": "líneas",
    "ingles": "inglés", "Ingles": "Inglés", "espanol": "español", "Espanol": "Español",
    "alli": "allí", "Bogota": "Bogotá", "Medellin": "Medellín",
    "Andres": "Andrés", "Perez": "Pérez", "Lopez": "López",
    "Fabrica": "Fábrica", "Maquinaria": "Maquinaria",
    "Aereo": "Aéreo", "aereo": "aéreo",
    "Ejecucion": "Ejecución", "ejecucion": "ejecución",
    "Anulada": "Anulada", "anulo": "anuló",
    "reembolso_n": "reembolso",
    "Reembolsado": "Reembolsado",
    "Transferencia": "Transferencia",
    "Region": "Región", "region": "región",
    "Mi abuelo": "Mi abuelo",
    "Reunion": "Reunión", "reunion": "reunión",
    "Coordinacion": "Coordinación", "coordinacion": "coordinación",
    "Nutricion": "Nutrición", "nutricion": "nutrición",
    "Decision": "Decisión", "decision": "decisión",
    "Suscripcion": "Suscripción",
    "Capacitacion": "Capacitación", "capacitacion": "capacitación",
    "Formacion": "Formación", "formacion": "formación",
    "Ubicacion": "Ubicación", "ubicacion": "ubicación",
    "Duracion": "Duración", "duracion": "duración",
    "Relacion": "Relación", "relacion": "relación", "relaciones": "relaciones",
    "Operacion": "Operación", "operacion": "operación", "operaciones": "operaciones",
    "Solicitud": "Solicitud",
    "Devolucion": "Devolución",
    "Anulacion": "Anulación",
    "Emision": "Emisión", "emision": "emisión",
    "Revision": "Revisión", "revision": "revisión",
    "Tension": "Tensión",
    "Extension": "Extensión",
    "Comision": "Comisión", "comision": "comisión",
    "Division": "División",
    "Mision": "Misión",
    "Vision": "Visión",
    "Presion": "Presión", "presion": "presión",
    "Sugerencia": "Sugerencia",
    "Metodologia": "Metodología", "metodologia": "metodología",
    "Estrategia": "Estrategia",
    "Ingenieria": "Ingeniería",
    "Mineria": "Minería", "mineria": "minería",
    "Agroindustria": "Agroindustria",
    "Financieros": "Financieros",
    "Profesionales": "Profesionales",
    "todavia": "todavía", "Todavia": "Todavía",
    "dolar": "dólar", "dolares": "dólares", "Dolar": "Dólar", "Dolares": "Dólares",
    "Pacifico": "Pacífico", "pacifico": "pacífico",
    "recien": "recién", "Recien": "Recién",
    "atras": "atrás", "Atras": "Atrás",
    "cuanto": "cuánto", "Cuanto": "Cuánto", "cuantos": "cuántos", "Cuantos": "Cuántos",
    "cuanta": "cuánta", "cuantas": "cuántas",
    "ahi": "ahí", "Ahi": "Ahí",
    "titulo": "título", "Titulo": "Título", "titulos": "títulos", "Titulos": "Títulos",
    "movil": "móvil", "Movil": "Móvil", "moviles": "móviles",
    "grafica": "gráfica", "graficas": "gráficas", "grafico": "gráfico", "graficos": "gráficos",
    "analisis": "análisis", "Analisis": "Análisis",
    "rapidamente": "rápidamente", "unicamente": "únicamente", "facilmente": "fácilmente",
    "tecnica": "técnica", "tecnico": "técnico", "Tecnico": "Técnico", "Tecnica": "Técnica",
    "tecnicas": "técnicas", "tecnicos": "técnicos",
    "estadistica": "estadística", "estadisticas": "estadísticas",
    "compania": "compañía", "Compania": "Compañía", "companias": "compañías",
    "diseno": "diseño", "Diseno": "Diseño",
    "senal": "señal", "senales": "señales", "Senal": "Señal", "Senales": "Señales",
    "pequeno": "pequeño", "pequenos": "pequeños", "pequena": "pequeña", "pequenas": "pequeñas",
    "dueno": "dueño", "duenos": "dueños",
    "extrano": "extraño",
    "acompanamiento": "acompañamiento", "Acompanamiento": "Acompañamiento",
    "envio": "envío", "Envio": "Envío",
    "entro": "entró", "Entro": "Entró",
    "aparecio": "apareció", "Aparecio": "Apareció",
    "habia": "había", "Habia": "Había",
    "economia": "economía", "Economia": "Economía",
    "energias": "energías",
    "quiza": "quizá",
    "parrafo": "párrafo", "parrafos": "párrafos",
    "numerico": "numérico", "numerica": "numérica",
    "dinamico": "dinámico", "estatico": "estático",
    "Atribucion": "Atribución",
    "atribucion": "atribución",
    "Conversacion": "Conversación",
    "conversacion": "conversación",
    "Conversion": "Conversión",
    "conversion": "conversión",
    "Interaccion": "Interacción",
    "interaccion": "interacción",
    "Navegacion": "Navegación",
    "navegacion": "navegación",
    "Normalizacion": "Normalización",
    "normalizacion": "normalización",
    "Produccion": "Producción",
    "produccion": "producción",
    "Promocion": "Promoción",
    "promocion": "promoción",
    "aprobacion": "aprobación",
    "Aprobacion": "Aprobación",
    "comprobacion": "comprobación",
    "Comprobacion": "Comprobación",
    "convencion": "convención",
    "Convencion": "Convención",
    "creacion": "creación",
    "Creacion": "Creación",
    "deduplicacion": "deduplicación",
    "demostracion": "demostración",
    "Demostracion": "Demostración",
    "disposicion": "disposición",
    "Disposicion": "Disposición",
    "edicion": "edición",
    "Edicion": "Edición",
    "ejecucion": "ejecución",
    "Ejecucion": "Ejecución",
    "expansion": "expansión",
    "Expansion": "Expansión",
    "explicacion": "explicación",
    "Explicacion": "Explicación",
    "exportacion": "exportación",
    "Exportacion": "Exportación",
    "funcion": "función",
    "Funcion": "Función",
    "impresion": "impresión",
    "Impresion": "Impresión",
    "instalacion": "instalación",
    "Instalacion": "Instalación",
    "migracion": "migración",
    "Migracion": "Migración",
    "moderacion": "moderación",
    "motivacion": "motivación",
    "Motivacion": "Motivación",
    "notificacion": "notificación",
    "Notificacion": "Notificación",
    "precision": "precisión",
    "Precision": "Precisión",
    "puntuacion": "puntuación",
    "Puntuacion": "Puntuación",
    "redireccion": "redirección",
    "Redireccion": "Redirección",
    "seccion": "sección",
    "Seccion": "Sección",
    "tabulacion": "tabulación",
    "ubicacion": "ubicación",
    "Ubicacion": "Ubicación",
    "PROXIMA": "PRÓXIMA", "ACCION": "ACCIÓN", "FACTURACION": "FACTURACIÓN",
    "INFORMACION": "INFORMACIÓN", "SESION": "SESIÓN",
}

# Frases donde la palabra es ambigua y hay que decidir por contexto.
PHRASES = [
    ("Se paso la fecha", "Se pasó la fecha"),
    ("Que esta pasando", "Qué está pasando"),
    ("QUE ESTA PASANDO", "QUÉ ESTÁ PASANDO"),
    ("Que hacer", "Qué hacer"),
    ("QUE HACER", "QUÉ HACER"),
    ("Que hay que hacer", "Qué hay que hacer"),
    ("Que sigue", "Qué sigue"),
    ("Que fue", "Qué fue"),
    ("Que quieres ver", "Qué quieres ver"),
    ("Que estas registrando", "Qué estás registrando"),
    ("Que va a pasar", "Qué va a pasar"),
    ("Que vas a importar", "Qué vas a importar"),
    ("Que cambio", "Qué cambió"),
    ("Que servicio se entrega", "Qué servicio se entrega"),
    ("Que conviene atender", "Qué conviene atender"),
    ("Que hace la sincronización", "Qué hace la sincronización"),
    ("Que hace el sistema por su cuenta", "Qué hace el sistema por su cuenta"),
    ("Que necesita contactar", "Qué necesita contactar"),
    ("Que se muestra", "Qué se muestra"),
    ("Que producto", "Qué producto"),
    ("Que pasa", "Qué pasa"),
    ("Como quedo", "Cómo quedó"),
    ("Como se calculan", "Cómo se calculan"),
    ("Como habilitarla", "Cómo habilitarla"),
    ("Como preparar el archivo", "Cómo preparar el archivo"),
    ("Como te ve el resto", "Cómo te ve el resto"),
    ("Como lo reconoces", "Cómo lo reconoces"),
    ("Como se comporta", "Cómo se comporta"),
    ("De donde salió", "De dónde salió"),
    ("DE DONDE SALIO", "DE DÓNDE SALIÓ"),
    ("de donde sale", "de dónde sale"),
    ("de donde salen", "de dónde salen"),
    ("de donde viene", "de dónde viene"),
    ("Cuando\"", "Cuándo\""),
    ("esta al día", "está al día"),
    ("estan al día", "están al día"),
    ("no esta ", "no está "),
    ("no está conectado", "no está conectado"),
    ("todavía no esta", "todavía no está"),
    ("ya esta ", "ya está "),
    ("esta pendiente", "está pendiente"),
    ("esta quieto", "está quieto"),
    ("esta conectada", "está conectada"),
    ("esta configurada", "está configurada"),
    ("esta marcada", "está marcada"),
    ("esta ligado", "está ligado"),
    ("esta fijado", "está fijado"),
    ("esta filtrada", "está filtrada"),
    ("esta agendado", "está agendado"),
    ("esta cerrado", "está cerrado"),
    ("esta parado", "está parado"),
    ("esta en la lista", "está en la lista"),
    ("esta usando", "está usando"),
    ("Esta accion", "Esta acción"),
    ("El correo lo cambia", "El correo lo cambia"),
]

PROP_KEYS = (
    "title|description|label|hint|placeholder|message|emptyTitle|emptyMessage|"
    "confirmLabel|cancelLabel|aria-label|searchPlaceholder|help|detail|evidence|"
    "success|summary|then|when|tagline|alt|noun|body"
)

def apply(text: str) -> str:
    for a, b in PHRASES:
        text = text.replace(a, b)
    for a, b in WORDS.items():
        if a.endswith("_v"):
            continue
        text = re.sub(rf"(?<![\w\-/áéíóúñÁÉÍÓÚÑ]){re.escape(a)}(?![\w\-/áéíóúñÁÉÍÓÚÑ])", b, text)
    return text

def process(path: pathlib.Path) -> bool:
    src = path.read_text(encoding="utf-8")
    out = src

    # 1. Texto entre etiquetas JSX: >texto<
    def jsx(m):
        inner = m.group(1)
        if any(ch in inner for ch in "{}<>=\"'`"):
            return m.group(0)
        if not re.search(r"[A-Za-z]{3}", inner):
            return m.group(0)
        return ">" + apply(inner) + "<"

    out = re.sub(r">([^<>{}]+)<", jsx, out)

    # 2. Propiedades de presentacion: label="…" / title={"…"} y sus variantes.
    def prop(m):
        return m.group(1) + apply(m.group(2)) + m.group(3)

    out = re.sub(rf'\b({PROP_KEYS})=(?:")([^"\n]*)(")', lambda m: f'{m.group(1)}="{apply(m.group(2))}"', out)
    out = re.sub(rf"\b({PROP_KEYS}):\s*\"([^\"\n]*)\"", lambda m: f'{m.group(1)}: "{apply(m.group(2))}"', out)

    # 3. Mensajes de error y avisos.
    out = re.sub(r'fail\("([^"\n]*)"', lambda m: f'fail("{apply(m.group(1))}"', out)
    out = re.sub(r'toast\.(success|error)\("([^"\n]*)"',
                 lambda m: f'toast.{m.group(1)}("{apply(m.group(2))}"', out)
    out = re.sub(r'new Error\("([^"\n]*)"', lambda m: f'new Error("{apply(m.group(1))}"', out)

    if out != src:
        path.write_text(out, encoding="utf-8")
        return True
    return False

changed = []
if __name__ == "__main__":
  for folder in sys.argv[1:]:
    for p in pathlib.Path(folder).rglob("*"):
      if p.suffix in (".tsx", ".ts") and p.is_file():
        if process(p):
          changed.append(str(p))
  print(f"{len(changed)} archivos ajustados")
